---
- name: Execute backup script on Docker container
  hosts: localhosts
  roles:
    - name: set_variables
    - name: set_docker_volume_version
  tasks:
    - name: Execute backup script
      command: docker exec {{ DOMAIN_NAME }}-backup sh -c 'DOCKER_VOLUME_VERSION={{ DOCKER_VOLUME_VERSION }} /workspace/backup.sh'
